[tool.poetry]
name = "scripts"
version = "1.0.0"
description = "ğŸš My personal automation scripts"
authors = ["Matthew Gleich <matthewgleich@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.3"
beautysh = "^6.0.1"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
